### ISSUE TITLE
Florb request.

### ISSUE THREAD

**Issue by 4fury-c3440d8** [FabioLolix/PKGBUILD#28]
florb is a lightweight map viewer and gpx editor written in FLTK. It was removed from AUR repository since 07.09.2024. Recently, several important fixes were released for it. Be an offend if the community forgot about this program. Is it possible to return it to repository?

[florb github repo](https://github.com/shugaa/florb).

[Various](https://codeberg.org/side/side/src/branch/master/runtime/gui/florb) [build specs](https://github.com/pisilinux/main/tree/master/network/misc/florb) for pisi p.m.

**Comment by FabioLolix** [comment]
Hi, generally you should ask here https://bbs.archlinux.org/viewforum.php?id=38

Honestly I don't have an use case for this program and already have quite a lot of stuff

> Is it possible to return it to repository?

I've took a quick look, upstream is inactive for 5 years now, please apply the patches to your fork https://github.com/4fury-c3440d8/florb then I'll look further

**Comment by 4fury-c3440d8** [comment]
> apply the patches to your fork

I can't.

**Comment by FabioLolix** [comment]
btw if you modify the messages I will not be notified

***

The program have fail,

```
==> Starting package()...
*** omake: reading OMakefiles
*** omake: finished reading OMakefiles (0.12 sec)
- build . <install>
+ global.foreach((fun public.t =>
                    shell(("mkdir",
                           ' ',
                           "-p",
                           ' ',
                           $(global.LOCALEDIR),
                           "/",
                           $(public.t),
                           "/LC_MESSAGES/"))
                    shell(("install",
                           ' ',
                           "./i18n/",
                           $(public.t),
                           "/florb.mo",
                           ' ',
                           $(global.LOCALEDIR),
                           "/",
                           $(public.t),
                           "/LC_MESSAGES/"))),
     $(global.basename $(global.TRANSLATIONS)))
/usr/bin/install: cannot stat './i18n/sv_SE/florb.mo': No such file or directory
*** omake error:
   File OMakefile: line 100, characters 2-61
   command terminated with code 1: install ./i18n/sv_SE/florb.mo /home/fabio/Dev/Github/PKGBUILD-AUR_fix/f/florb-git/pkg/florb/usr/share/locale/sv_SE/LC_MESSAGES/

*** omake: 11/12 targets are up to date
*** omake: failed (0.16 sec, 0/0 scans, 1/1 rules, 0/37 digests)
*** omake: targets were not rebuilt because of errors:
   <phony <install>>
==> ERROR: A failure occurred in package().
```


`i18n/sv_SE/florb.mo` isn't created and it later fails when try to install

**Comment by 4fury-c3440d8** [comment]
Do you installed [python3-translate_toolkit](https://pypi.org/project/translate-toolkit/)?

**Comment by FabioLolix** [comment]
Tried again installing https://archlinux.org/packages/extra/any/translate-toolkit/ which seem the packaged version but the result didn't change

`de_DE/florb.mo` is created also without translate-toolkit

**Comment by 4fury-c3440d8** [comment]
I see. The translate-toolkit package from the arch repository does not list all required dependencies. See PKG_INFO in the source code. Needs wcwidth or, for the newest version, cwcwidth.

**Comment by FabioLolix** [comment]
Ok I got it https://aur.archlinux.org/packages/florb-git

**Comment by 4fury-c3440d8** [comment]
Thank You!

Please replace homepage of the florb package to https://github.com/shugaa/florb. By now I just added a few patches and do not can become an upstream of this project.
