### ISSUE TITLE
Let it support all browsers，please accept

### ISSUE THREAD

**Issue by xuelongqy** [FabioLolix/PKGBUILD#4]
Let it support all browsers base on  chromium.
Change "/usr/lib/chromium/libffmpeg.so" to "/usr/lib/chromium-browser/libffmpeg.so"

**Comment by FabioLolix** [comment]
Chromium is installed in "/usr/lib/chromium/"

"/usr/lib/chromium-browser/" is the same path seen on Ubuntu,

Which others browsers for example?

**Comment by xuelongqy** [comment]
Like Chromium,Yandex,Opera...

**Comment by FabioLolix** [comment]
Chromium already have ffmpeg built in, as you can see here: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/chromium

> 'ffmpeg_branding="Chrome"'
> 'proprietary_codecs=true'

and 

> readonly -A _system_libs=(
> #[ffmpeg]=ffmpeg            # https://crbug.com/731766

to know if ffmpeg library is working check bug https://crbug.com/731766 and try to watch link reported

I had built Chromium without builtin ffmpeg and it don't load libffmpeg.so so this package is pointless and have been deleted from the AUR

*** 
Opera, Yandex and Vivaldi have their package in the AUR or in the Herecura repository

**Comment by xuelongqy** [comment]
Ok, thank you.It's very helpful to me
