### ISSUE TITLE
strawberry updated to 0.4.1

### ISSUE THREAD

**Issue by ArielRosenfeld** [FabioLolix/PKGBUILD#6]
strawberry updated to 0.4.1 you might have missed the out of date flag or were busy

**Comment by FabioLolix** [comment]
Update will come tomorrow, for real

**Comment by FabioLolix** [comment]
AUR pkgbuilds updated

**Comment by ArielRosenfeld** [comment]
you forgot to close this after the update and its version 0.4.2 now

**Comment by FabioLolix** [comment]
Pkgbuilds have been updated to v0.4.2, there has been some changes and a new pkgbuild srawberry-lite created https://github.com/FabioLolix/PKGBUILD/commit/21b7d2ec4772cfd731879a79ad63ee1abc538479
