### ISSUE TITLE
Strawberry-git shouldn't use system taglib

### ISSUE THREAD

**Issue by Fef0** [FabioLolix/PKGBUILD#8]
Strawberry actually uses a modified version of taglib which supports DSD files, you should just change the -DUSE_SYSTEM_TAGLIB=ON flag to -DUSE_SYSTEM_TAGLIB=OFF, so the modified taglib could be used.
Here's the discussion for this specific problem on strawberry's github page: https://github.com/jonaski/strawberry/issues/152
This is the solution given by the author itself: https://github.com/jonaski/strawberry/issues/152#issuecomment-519694441

Thank you very much in advance.

**Comment by FabioLolix** [comment]
Hello, I have modified the pkgbuilds (also on the AUR) to use the embedded taglib 36e63eadb440d430542376135fd9fcab1fa0c9e2 and I have created another pkgbuild which use the system's taglib (not in the AUR)
